"""add_content_hash_and_pipeline_job_type

Revision ID: 002809346eb1
Revises: aa8f7a7ee565
Create Date: 2026-02-11 10:22:38.911910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002809346eb1'
down_revision: Union[str, None] = 'aa8f7a7ee565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_images_content_hash'), 'images', ['content_hash'], unique=True)
    # Add 'pipeline' value to jobtype enum (not auto-detected by Alembic)
    op.execute("ALTER TYPE jobtype ADD VALUE IF NOT EXISTS 'pipeline'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_content_hash'), table_name='images')
    op.drop_column('images', 'content_hash')
    # ### end Alembic commands ###
